### PR TITLE
Polish mount dir

### PR DESCRIPTION
**Pull request by fangohr**

### CODE REVIEW

**Comment by mhanberry1** [comment]
I've made some changes to fix the testing issues:
https://github.com/nmag-project/containers/pull/13

**Comment by fangohr** [comment]
Many thanks @mhanberry1 - this has taken us forward quite a bit.

There is a new errror message arising (https://github.com/nmag-project/containers/runs/3764972784?check_suite_focus=true#step:4:24) which I think is related: it looks like we are lacking permissions to write to the folder. 

I have two comments:

- it is unfortunate that our work flow doesn't fail despite the error that occurred (so the exit code isn't propagated up to higher levels somewhere)

- I suspect the problem we see could be fixed by creating a user in the container (similar to https://github.com/fangohr/oommf/blob/master/docker/Dockerfile).

**Comment by mhanberry1** [comment]
>     * it is unfortunate that our work flow doesn't fail despite the error that occurred (so the exit code isn't propagated up to higher levels somewhere)

docker returns the exit code of the command executed, but for some reason nsim exits with a success when there is an IO error. I think this is an implementation issue.

>     * I suspect the problem we see could be fixed by creating a user in the container (similar to https://github.com/fangohr/oommf/blob/master/docker/Dockerfile).

You're right. I think this could be fixed by adding adding a step that changes the directory permissions before the "run example in container" step. Here's a PR for that:
https://github.com/nmag-project/containers/pull/14

**Comment by fangohr** [comment]
That's great, thank you @mhanberry1 !

**Pull request merged**
