### PR TITLE
tidy up by moving non-working (Docker) attempts into archive

### PR DESCRIPTION
**Pull request by fangohr**
subdirectory.

### CODE REVIEW

**Comment by fangohr** [comment]
@mhanberry1 - can you review this?

**Review by mhanberry1 — APPROVED** [review]
Looks good.

**Comment by mhanberry1** [comment]
@fangohr FYI, I don't have the authority to merge this code because I don't have write access to this repository.

**Comment by fangohr** [comment]
@mhanberry1 - thanks; have just sent you an invite.

**Pull request merged**
